apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: news-platform
data:
  server.properties: |
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/var/lib/kafka/data
    num.partitions=3
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connection.timeout.ms=18000
    group.initial.rebalance.delay.ms=0
    auto.create.topics.enable=false
    delete.topic.enable=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics
  namespace: news-platform
data:
  topics.json: |
    {
      "topics": [
        {
          "name": "news.economy.raw",
          "partitions": 3,
          "replication_factor": 3,
          "config": {
            "retention.ms": 604800000,
            "cleanup.policy": "delete"
          }
        },
        {
          "name": "news.business.raw",
          "partitions": 3,
          "replication_factor": 3,
          "config": {
            "retention.ms": 604800000,
            "cleanup.policy": "delete"
          }
        },
        {
          "name": "news.society.raw",
          "partitions": 3,
          "replication_factor": 3,
          "config": {
            "retention.ms": 604800000,
            "cleanup.policy": "delete"
          }
        }
      ]
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: news-platform
spec:
  serviceName: zookeeper-svc
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.0
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-0.zookeeper-svc.news-platform.svc.cluster.local:2888:3888;zookeeper-1.zookeeper-svc.news-platform.svc.cluster.local:2888:3888;zookeeper-2.zookeeper-svc.news-platform.svc.cluster.local:2888:3888"
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: news-platform
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper 