apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-scheduler # ServiceAccount for the Airflow Scheduler pods
  namespace: news-platform
  labels:
    app: airflow
    component: scheduler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-worker # ServiceAccount for the dynamically created Airflow worker pods
  namespace: news-platform # Must match AIRFLOW__KUBERNETES__NAMESPACE
  labels:
    app: airflow
    component: worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-scheduler-role
  namespace: news-platform # This role applies to the namespace where worker pods will be created
  labels:
    app: airflow
    component: scheduler
rules:
  - apiGroups: [""] # Core API group
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  # Add other permissions if needed by your DAGs or Airflow setup
  # For example, if KubernetesPodOperator needs to manage services or other resources.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-scheduler-rb
  namespace: news-platform
  labels:
    app: airflow
    component: scheduler
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler # Grant permissions to the scheduler's ServiceAccount
    namespace: news-platform
roleRef:
  kind: Role
  name: airflow-scheduler-role # The Role created above
  apiGroup: rbac.authorization.k8s.io
# --- (Optional) If worker pods need specific (minimal) permissions, define a Role and RoleBinding for airflow-worker SA
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: airflow-worker-role
#   namespace: news-platform
# rules:
#   - apiGroups: [""]
#     resources: ["pods"]
#     verbs: ["patch"] # For updating pod annotations, e.g., with final status
#   - apiGroups: [""]
#     resources: ["secrets"]
#     verbs: ["get"] # If workers need to read secrets
# --- 
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: airflow-worker-rb
#   namespace: news-platform
# subjects:
#   - kind: ServiceAccount
#     name: airflow-worker
#     namespace: news-platform
# roleRef:
#   kind: Role
#   name: airflow-worker-role
#   apiGroup: rbac.authorization.k8s.io 