apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: news-platform
  labels:
    app: airflow
data:
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
  AIRFLOW__CORE__FERNET_KEY: ""  # 실제 배포 시 생성해서 채워넣어야 함
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: "Asia/Seoul"
  
  # Kubernetes Executor 설정
  AIRFLOW__KUBERNETES__NAMESPACE: "news-platform"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "2.10.5-python3.11"
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "true"
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "airflow"
  AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: "/opt/airflow/config/pod_template.yaml"
  AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "16"
  AIRFLOW__KUBERNETES__MULTI_NAMESPACE_MODE: "false"
  AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: '{"_request_timeout": [60, 60]}'
  
  # 성능 및 확장성 설정
  AIRFLOW__SCHEDULER__MAX_THREADS: "4"
  AIRFLOW__CELERY__WORKER_CONCURRENCY: "16"
  AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "60"
  AIRFLOW__SCHEDULER__PARSING_PROCESSES: "4"
  AIRFLOW__WEBSERVER__WORKERS: "4"
  
  # 로깅 및 모니터링
  AIRFLOW__LOGGING__REMOTE_LOGGING: "true"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://airflow-logs-bucket/logs"
  
  # 웹서버 설정
  AIRFLOW__WEBSERVER__SECRET_KEY: "news-pipeline-key"  # 실제 배포 시 변경해야 함
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "false"
  AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8081"
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
  
  # 캐싱 및 성능 최적화
  AIRFLOW__SCHEDULER__USE_JOB_SCHEDULE: "true"
  AIRFLOW__CORE__STORE_SERIALIZED_DAGS: "true"
  AIRFLOW__CORE__STORE_DAG_CODE: "true"
  AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: "30" 