apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow # Airflow를 배포할 네임스페이스 (필요시 수정)
type: Opaque
data:
  fernet-key: eGw2RC10dWk2eHJJU3d1WEZUNVRrTFpuTFhndjJ3SG5ZTXRzeDhHcG5Bbz0= # Base64 인코딩된 키 