apiVersion: v1
kind: Namespace
metadata:
  name: news-platform
  labels:
    name: news-platform
    environment: production
    app: news-processing-pipeline
  annotations:
    description: "뉴스 처리 파이프라인 애플리케이션을 위한 네임스페이스" 