apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: news-platform
  labels:
    app: news-processing
    type: models
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi 